server:
  port: 8091
spring:
  application:
    name: produits-service
  datasource:
    url: jdbc:postgresql://exam-postgres-1:5432/db_boutique
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  cache:
    type: none
eureka:
  client:
    service-url:
      defaultZone: http://exam-eureka-server-1:8761/eureka/
