server:
  port: 8092
spring:
  application:
    name: avis-service
  datasource:
    url: jdbc:postgresql://exam-postgres-1:5432/db_boutique
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://exam-eureka-server-1:8761/eureka/
